### ISSUE TITLE
chrX and chrY in GC mappability pipeline

### ISSUE THREAD

**Issue by savarsinha123** [adoebley/Griffin#15]
Hello,

I had a question about the GC mappability pipeline. When I looked through the scripts, it seems as though the GC bias is only calculated for chromosomes 1-22. Is there a way to also configure the GC mappability pipeline to work with the X and Y chromosomes as well, or does the pipeline only work with autosomes.

Thanks!
Savar Sinha

**Comment by adoebley** [comment]
Hi, Thank you for the question and sorry for the huge delay in responding. The GC bias is calculated for the whole sample and doesn't vary by chromosome. The X and Y are ignored when calculating GC bias because they aren't (always) present in 2 copies and this difference in coverage would change the GC bias if they were included.

**Comment by savarsinha123** [comment]
Ah I see, thank you for your response!
