### ISSUE TITLE
difficulties using your code

### ISSUE THREAD

**Issue by a-dna-n** [adoebley/Griffin#6]
Hi.

It would be great to apply your methods and code to new data, but I'm finding it very difficult. I've looked through all the scripts (yaml, Python and snakefile, though not the notebooks) in this repo and in `Griffin_analyses`.

- The readme in this repo refers to the `griffin_GC_correction` task and its corresponding `griffin_GC_correction.snakemake`, but that doesn't seem to exist. There's `griffin_GC_and_mappability_correction`, and by looking through the individual files, you can eventually learn (from `Griffin/snakemakes/griffin_GC_and_mappability_correction/config/config.yaml`) that mappability correction is disabled by default because it's not recommended.
- Even if mappability correction is not required, mappable regions are required for GC correction. The help text for `griffin_GC_counts.py` explains "--mappable_regions_path" as "highly mappable regions to be used in GC correction". Do I want all mappable regions, regions with score >= 0.95, or score = 1?
- There's a file in this repo with mappable regions but no scores (`k100_minus_exclusion_lists.mappable_regions.hg38.bed`) , so I can't tell if this is all mappable regions or a subset. The regions span 2.5 Gb, which sounds too high for highly mappable regions.
- The readme in this repo and the preprint refer to the `griffin_filter_sites` task/pipeline, and the readme mentions `griffin_filter_sites.snakefile`. I can't find anything resembling that in either repo. Did I miss it, or is it not available?
- According to the readme, the outputs of `griffin_filter_sites` include files for sites with high and low map(p)ability. I can't find any reference to these files in file names or scripts in either repo (with or without the double p), so I can't follow how this step is connected to anything else.
- Masking repeats sounds like a no-brainer that other methods have surprisingly ignored. I'd like to see what difference it makes, but I'm not able to understand where Repeatmasker results enter the pipeline. The readme says that the outputs of GC correction land in a subdirectory named `repeat_masker...` , but I don't see any mention of that in file names or scripts, even if I try "repeat" and "mask" individually. I even searched for `hgTable`.

If you'd like others to use your code (and cite your paper), and it makes things easier, I'd suggest dropping snakemake.

**Comment by adoebley** [comment]
Hi, 

Thank you for reaching out with the comments and suggestions and sorry for the delay in responding! I'd recommend you try running the demo (in the wiki) since I think it might answer a lot of your questions.

I've updated the readme to reflect the steps in the current version of the pipeline (we're in the process of doing revisions and some things have changed, hopefully we should have the final version of the paper available in the near future). The current order of steps is:
1. griffin_genome_GC_frequncy (already complete if you're using hg38)
2. griffin_GC_and_mappability_correction (mappability correction is turned off by default)
3. griffin_nucleosome_profiling 

`griffin_filter_sites` is no longer part of the pipeline and I removed it from the readme. 

The mappable regions file used for  "--mappable_regions_path" in the griffin_GC_and_mappability_correction step is specified in the config:
mappable_regions: ../../Ref/k100_minus_exclusion_lists.mappable_regions.hg38.bed
This contains each position with a mappability score of 1 that doesn't overlap centromeres, gaps, fix patches, alternative haplotypes, and excluded regions.
We took out the repeat masker filter because we found that we could get rid of the regions that were causing problems with the above filters rather than needing to exclude all repeats. I've removed it from the readme.

And we are working on a WDL pipeline as an alternative to the snakemake but I think it's going to be a while before that is available. 

Let me know if you have any further questions.
