### ISSUE TITLE
Missing Script for Running 'griffin_filter_sites' Pipeline to Generate Sites File

### ISSUE THREAD

**Issue by yueyaog** [adoebley/Griffin#9]
Hi Developer,

Thank you for creating such a valuable tool for tumor subtype classification. It's really helpful in my work. However, I noticed that there's no script available in the repo for generating the sites file. In the manuscript, you mentioned the 'griffin_filter_sites' pipeline as the way to perform this filtration, but I couldn't locate the corresponding script to run it.

I would greatly appreciate it if you could provide some guidance on how to generate the sites file. Thank you for your time and effort in maintaining this repo.

Best,
Gao

**Comment by yueyaog** [comment]
I have the sites files that were used in the paper which is located in [adoebley/Griffin_analyses](https://github.com/adoebley/Griffin_analyses/blob/main/sites/TFBS/30000_unfiltered_sites_CIS_BP_v2/).

**Comment by adoebley** [comment]
Hi Gao, 

Thanks for the question and sorry for the long delay in getting back to you! In our biorxiv manuscript (griffin github release v0.1.0) we filtered sites ('griffin_filter_sites') prior to analysis, however, we changed this in response to reviewer suggestions. 

The current version of Griffin on github (v0.2.0, which corresponds to the published paper) doesn't require site filtration prior to analysis. It ignores coverage at individual bp within sites if they are unmappable or otherwise flagged as excluded (e.x. centromeres, gaps, encode exclusion list, patches, and alternative haplotypes). 

If you want to make your own site lists, I'd recommend checking out the format in the demo file:
https://github.com/adoebley/Griffin/blob/main/demo/griffin_nucleosome_profiling_demo_files/sites/CTCF.hg38.1000.txt

The [adoebley/Griffin_analyses](https://github.com/adoebley/Griffin_analyses/blob/main/sites/TFBS/30000_unfiltered_sites_CIS_BP_v2/) github that you used also has the correct format.

Let me know if you have more questions,
Anna-Lisa
